import { ChangeEvent, PointerEvent, useEffect, useRef, useState } from "react";
import * as pdfjs from "pdfjs-dist";
import pdfWorker from "pdfjs-dist/build/pdf.worker.min.mjs?url";

pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;

type Tool = "pen" | "marker" | "eraser" | "text";
type Point = { x:number; y:number };
type Stroke = { id:number; points:Point[]; color:string; width:number; opacity:number };
type TextNote = { id:number; x:number; y:number; text:string };
type PageInfo = { number:number; width:number; height:number; page:pdfjs.PDFPageProxy|null; imageData?:string };
type HistoryItem = { id:number; name:string; kind:"blank"|"pdf"; createdAt:string; updatedAt:string };
const icons:Record<string,string>={pen:"M15 5l4 4M4 20l4.5-1 10-10a2.8 2.8 0 00-4-4l-10 10L4 20Z",marker:"M14 4l6 6-9 9H5v-6l9-9Z M4 20h10",eraser:"M7 19l-3-3L14 4l6 6-8 9H7Z M11 19l-4-4",text:"M5 5V3h14v2M12 3v18M9 21h6",undo:"M9 8l-5 4 5 4M5 12h8a6 6 0 016 6",redo:"M15 8l5 4-5 4M19 12h-8a6 6 0 00-6 6",upload:"M12 16V4m0 0L7 9m5-5l5 5M4 15v5h16v-5",plus:"M12 5v14M5 12h14",minus:"M5 12h14",home:"M4 11l8-7 8 7v9h-6v-6h-4v6H4Z",file:"M6 3h8l4 4v14H6V3Zm8 0v5h5",blank:"M5 3h14v18H5V3Z"};
const Icon=({name}:{name:string})=><svg viewBox="0 0 24 24"><path d={icons[name]}/></svg>;

function PdfPage({info,children}:{info:PageInfo;children:React.ReactNode}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{if(!info.page||!ref.current)return;const canvas=ref.current,scale=2,viewport=info.page.getViewport({scale});canvas.width=viewport.width;canvas.height=viewport.height;const ctx=canvas.getContext("2d");if(!ctx)return;const task=info.page.render({canvasContext:ctx,viewport});return()=>task.cancel()},[info.page]);
  const margin=info.page?220:0;
  return <div className={`page-paper ${info.page?"with-notes":""}`} style={{width:info.width+margin*2,height:info.height}}>{info.page&&<div className="margin-hint left">Notes</div>}<canvas ref={ref} style={{left:margin,width:info.width}}/>{info.imageData&&<img className="blank-image" src={info.imageData} alt="Imported"/>}{info.page&&<div className="margin-hint right">Notes</div>}{children}</div>
}

function NoteEditor({note,color,bounds,onChange,onMove,onDelete}:{note:TextNote;color:string;bounds:{width:number;height:number};onChange:(text:string)=>void;onMove:(x:number,y:number)=>void;onDelete:()=>void}){
  const ref=useRef<HTMLTextAreaElement>(null);
  const drag=useRef<{clientX:number;clientY:number;x:number;y:number;ratio:number}|null>(null);
  useEffect(()=>{ref.current?.focus()},[]);
  const dragStart=(e:PointerEvent<HTMLDivElement>)=>{e.preventDefault();e.stopPropagation();const paper=e.currentTarget.closest(".page-paper")!.getBoundingClientRect();drag.current={clientX:e.clientX,clientY:e.clientY,x:note.x,y:note.y,ratio:bounds.width/paper.width};const move=(event:globalThis.PointerEvent)=>{const d=drag.current;if(!d)return;onMove(Math.max(0,Math.min(bounds.width-190,d.x+(event.clientX-d.clientX)*d.ratio)),Math.max(0,Math.min(bounds.height-110,d.y+(event.clientY-d.clientY)*d.ratio)))};const end=()=>{drag.current=null;document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",end);document.removeEventListener("pointercancel",end)};document.addEventListener("pointermove",move);document.addEventListener("pointerup",end);document.addEventListener("pointercancel",end)};
  return <div className="text-note" style={{left:note.x,top:note.y,color}} onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()}><div className="note-handle" title="Drag to move" onPointerDown={dragStart}><span>•••</span><button title="Delete note" onPointerDown={e=>e.stopPropagation()} onClick={onDelete}>×</button></div><textarea ref={ref} value={note.text} placeholder="Type a note…" onChange={e=>onChange(e.target.value)}/></div>;
}

export default function App(){
  const [mode,setMode]=useState<"start"|"history"|"editor">("start"),[name,setName]=useState("Untitled board"),[pages,setPages]=useState<PageInfo[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [projectId,setProjectId]=useState<number|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[saved,setSaved]=useState(true);
  const [projectKind,setProjectKind]=useState<"blank"|"pdf">("blank");
  const [tool,setTool]=useState<Tool>("pen"),[color,setColor]=useState("#252525"),[zoom,setZoom]=useState(85),[strokes,setStrokes]=useState<Record<number,Stroke[]>>({}),[notes,setNotes]=useState<Record<number,TextNote[]>>({}),[redo,setRedo]=useState<{page:number;stroke:Stroke}[]>([]),[drawing,setDrawing]=useState<{page:number;active:boolean}|null>(null);
  const input=useRef<HTMLInputElement>(null),imageInput=useRef<HTMLInputElement>(null),id=useRef(0);
  const createRecord=async(payload:object)=>{const r=await fetch("/api/boards",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();return (await r.json()).id as number};
  const blank=async()=>{try{const initial=[{number:1,width:900,height:1200,page:null}];const id=await createRecord({name:"Untitled board",kind:"blank",state:{strokes:{},notes:{},pages:initial}});setProjectId(id);setProjectKind("blank");setName("Untitled board");setPages(initial);setStrokes({});setNotes({});setRedo([]);setSaved(true);setMode("editor")}catch{setError("无法连接本地存储服务。")} };
  const renderPdf=async(data:Uint8Array)=>{const doc=await pdfjs.getDocument({data}).promise,next:PageInfo[]=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),v=page.getViewport({scale:1.2});next.push({number:n,width:v.width,height:v.height,page})}return next};
  const importPdf=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setLoading(true);setError("");try{const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer),next=await renderPdf(bytes.slice()),pdfBase64=btoa(Array.from(bytes,b=>String.fromCharCode(b)).join("")),boardName=file.name.replace(/\.pdf$/i,"");const id=await createRecord({name:boardName,kind:"pdf",pdfBase64,state:{strokes:{},notes:{}}});setProjectId(id);setProjectKind("pdf");setName(boardName);setPages(next);setStrokes({});setNotes({});setRedo([]);setSaved(true);setMode("editor")}catch{setError("无法读取或保存这个 PDF，请重试。")}finally{setLoading(false);e.target.value=""}};
  const showHistory=async()=>{setLoading(true);try{const r=await fetch("/api/boards");setHistory(await r.json());setMode("history")}catch{setError("无法读取历史记录。")}finally{setLoading(false)}};
  const openHistory=async(id:number)=>{setLoading(true);try{const r=await fetch(`/api/boards/${id}`),item=await r.json();const next=item.kind==="pdf"?await renderPdf(Uint8Array.from(atob(item.pdfBase64),c=>c.charCodeAt(0))):(item.state.pages||[{number:1,width:900,height:1200,page:null}]);setProjectId(item.id);setProjectKind(item.kind);setName(item.name);setPages(next);setStrokes(item.state.strokes||{});setNotes(item.state.notes||{});setRedo([]);setSaved(true);setMode("editor")}finally{setLoading(false)}};
  const deleteHistory=async(id:number)=>{await fetch(`/api/boards/${id}`,{method:"DELETE"});setHistory(items=>items.filter(item=>item.id!==id))};
  useEffect(()=>{if(mode!=="editor"||!projectId)return;setSaved(false);const timer=setTimeout(async()=>{try{const savedPages=projectKind==="blank"?pages.map(({number,width,height,imageData})=>({number,width,height,page:null,imageData})):undefined;await fetch(`/api/boards/${projectId}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,state:{strokes,notes,pages:savedPages}})});setSaved(true)}catch{}},600);return()=>clearTimeout(timer)},[strokes,notes,pages,name,projectId,projectKind,mode]);
  const addBlankPage=()=>setPages(current=>[...current,{number:current.length+1,width:900,height:1200,page:null}]);
  const importImage=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setPages(current=>[...current,{number:current.length+1,width:900,height:1200,page:null,imageData:String(reader.result)}]);reader.readAsDataURL(file);e.target.value=""};
  const point=(e:PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect(),view=e.currentTarget.viewBox.baseVal;return{x:(e.clientX-r.left)*view.width/r.width,y:(e.clientY-r.top)*view.height/r.height}};
  const start=(page:number,e:PointerEvent<SVGSVGElement>)=>{if(tool==="text")return;const p=point(e);e.currentTarget.setPointerCapture(e.pointerId);setDrawing({page,active:true});setRedo([]);setStrokes(all=>({...all,[page]:[...(all[page]||[]),{id:id.current++,points:[p],color:tool==="eraser"?"#fff":tool==="marker"?"#f5c94a":color,width:tool==="eraser"?28:tool==="marker"?16:3.5,opacity:tool==="marker"?.45:1}]}))};
  const addText=(page:number,width:number,height:number,e:React.MouseEvent<SVGSVGElement>)=>{if(tool!=="text")return;const r=e.currentTarget.getBoundingClientRect(),view=e.currentTarget.viewBox.baseVal;const x=(e.clientX-r.left)*view.width/r.width,y=(e.clientY-r.top)*view.height/r.height;setNotes(all=>({...all,[page]:[...(all[page]||[]),{id:id.current++,x:Math.max(8,Math.min(x,width-190)),y:Math.max(8,Math.min(y,height-85)),text:""}]}))};
  const move=(page:number,e:PointerEvent<SVGSVGElement>)=>{if(!drawing?.active||drawing.page!==page)return;const p=point(e);setStrokes(all=>({...all,[page]:(all[page]||[]).map((s,i,a)=>i===a.length-1?{...s,points:[...s.points,p]}:s)}))};
  const undo=()=>{const entries=Object.entries(strokes).filter(([,v])=>v.length);if(!entries.length)return;const [p,list]=entries.at(-1)!;const last=list.at(-1)!;setStrokes(s=>({...s,[p]:s[+p].slice(0,-1)}));setRedo(r=>[...r,{page:+p,stroke:last}])};
  const redoOne=()=>{const item=redo.at(-1);if(!item)return;setStrokes(s=>({...s,[item.page]:[...(s[item.page]||[]),item.stroke]}));setRedo(r=>r.slice(0,-1))};
  const updateNote=(page:number,noteId:number,text:string)=>setNotes(all=>({...all,[page]:(all[page]||[]).map(n=>n.id===noteId?{...n,text}:n)}));
  const moveNote=(page:number,noteId:number,x:number,y:number)=>setNotes(all=>({...all,[page]:(all[page]||[]).map(n=>n.id===noteId?{...n,x,y}:n)}));
  const deleteNote=(page:number,noteId:number)=>setNotes(all=>({...all,[page]:(all[page]||[]).filter(n=>n.id!==noteId)}));
  const path=(p:Point[])=>p.map((v,i)=>`${i?"L":"M"}${v.x} ${v.y}`).join(" ");
  if(mode==="start")return <main className="welcome"><header><div className="brand"><b>◒</b> Margin</div><button className="history-link" onClick={showHistory}>History</button></header><div className="welcome-card"><div className="welcome-mark">◒</div><h1>What do you want to work on?</h1><p>Import a PDF to annotate page by page, or start fresh with a blank canvas.</p><div className="start-actions"><button className="pdf-choice" onClick={()=>input.current?.click()} disabled={loading}><span><Icon name="file"/></span><strong>{loading?"Reading PDF…":"Import PDF"}</strong><small>Open and annotate every page</small></button><button onClick={blank}><span><Icon name="blank"/></span><strong>Create blank</strong><small>Start with an empty page</small></button></div>{error&&<div className="error">{error}</div>}<button className="view-history" onClick={showHistory}>View history</button><small className="formats">Saved locally with SQLite</small></div><input ref={input} hidden type="file" accept="application/pdf" onChange={importPdf}/></main>;
  if(mode==="history")return <main className="history-page"><header><div className="brand"><b>◒</b> Margin</div><h2>History</h2><button className="history-link" onClick={()=>setMode("start")}>New board</button></header><section className="history-content"><div className="history-heading"><div><h1>Your boards</h1><p>Continue where you left off.</p></div><span>{history.length} projects</span></div>{loading?<div className="history-empty">Loading…</div>:history.length===0?<div className="history-empty"><Icon name="blank"/><h3>No history yet</h3><p>Create a blank board or import a PDF to get started.</p></div>:<div className="history-grid">{history.map(item=><article key={item.id}><button className="history-open" onClick={()=>openHistory(item.id)}><div className={`history-icon ${item.kind}`}><Icon name={item.kind==="pdf"?"file":"blank"}/></div><strong>{item.name}</strong><small>{item.kind.toUpperCase()} · {new Date(item.updatedAt+"Z").toLocaleString()}</small></button><button className="history-delete" onClick={()=>deleteHistory(item.id)} title="Delete">×</button></article>)}</div>}</section></main>;
  return <main className={`editor tool-${tool}`}><header><div className="brand"><b>◒</b> Margin</div><div className="title"><strong>{name}</strong><small>{saved?"● Saved locally":"● Saving…"} · {pages.length} {pages.length===1?"page":"pages"}</small></div><div className="actions">{projectKind==="blank"&&<><button onClick={addBlankPage}><Icon name="plus"/>Add page</button><button onClick={()=>imageInput.current?.click()}><Icon name="upload"/>Import image</button></>}<button onClick={()=>setMode("start")}><Icon name="home"/>Home</button></div></header><input ref={imageInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={importImage}/><aside>{(["pen","marker","eraser","text"] as Tool[]).map(t=><button key={t} className={tool===t?"active":""} onClick={()=>setTool(t)} title={t}><Icon name={t}/></button>)}<hr/><label><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><span style={{background:color}}/></label><hr/><button onClick={undo} disabled={!Object.values(strokes).some(v=>v.length)}><Icon name="undo"/></button><button onClick={redoOne} disabled={!redo.length}><Icon name="redo"/></button></aside>{tool==="text"&&<div className="text-tip">Click to add text · Drag the top bar to move it</div>}<section className="document-space"><div className="pages" style={{transform:`scale(${zoom/100})`}}>{pages.map(info=>{const surfaceWidth=info.width+(info.page?440:0);return <div className="page-wrap" key={info.number}><div className="page-label">Page {info.number} of {pages.length}</div><PdfPage info={info}><svg className="drawing" viewBox={`0 0 ${surfaceWidth} ${info.height}`} onClick={e=>addText(info.number,surfaceWidth,info.height,e)} onPointerDown={e=>start(info.number,e)} onPointerMove={e=>move(info.number,e)} onPointerUp={()=>setDrawing(null)} onPointerCancel={()=>setDrawing(null)}>{(strokes[info.number]||[]).map(s=><path key={s.id} d={path(s.points)} fill="none" stroke={s.color} strokeWidth={s.width} strokeOpacity={s.opacity}/>)}</svg>{(notes[info.number]||[]).map(n=><NoteEditor key={n.id} note={n} color={color} bounds={{width:surfaceWidth,height:info.height}} onChange={text=>updateNote(info.number,n.id,text)} onMove={(x,y)=>moveNote(info.number,n.id,x,y)} onDelete={()=>deleteNote(info.number,n.id)}/>)}</PdfPage></div>})}</div></section><div className="zoom"><button onClick={()=>setZoom(z=>Math.max(40,z-10))}><Icon name="minus"/></button><span>{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(150,z+10))}><Icon name="plus"/></button><button onClick={()=>setZoom(85)}>Fit</button></div></main>
}
